[[rule]]
[rule.formatting]
align_entries         = true
compact_entries       = false
compact_inline_tables = false
indent_string         = "    "
reorder_arrays        = true
reorder_keys          = true
